import { Typography } from '@mui/material';
import Head from 'next/head';
import React from 'react';


const contact = () => {
    
  return (
    <div>
        <Head>
        <title>Contact | Empiya - Send and receive money</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <Typography variant='h4'>Contact us</Typography>
    </div>
  )
}

export default contact;
