import { useEffect } from 'react';
import { useRouter } from 'next/router';
import { Box, Divider } from '@mui/material';
import Head from 'next/head';
import Buy from './hero/buy';
import Sidebar from './hero/sidebar';
import HeroText from './hero/HeroText';
import Converter from '../../Component/empiyaConvert';

export default function Home() {
  const router = useRouter();

  // useEffect(() => {
  //   const isLoggedIn = true;

  //   if (isLoggedIn) {
  //     // User is logged in, display an alert
  //     alert('You are already logged in!');
  //   } else {
  //     // User is not logged in, redirect to the login page
  //     router.push('/signup');
  //   }
  // }, []);

  return (
    <>
      <Head>
        <title>Empiya | Send and receive money</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box display={['block', 'block', 'flex']} justifyContent="space-between" padding={['2rem 0', '3rem 0']}>
          <Sidebar />
          <Converter />
          <HeroText/>
        </Box>
        <Box padding={['1rem 2rem', '1rem 2rem', '1rem 12rem']}>
          <Divider color="#323a40" sx={{ borderBottomWidth: '.1px' }} />
        </Box>
      </main>
    </>
  );
}
